language: go

go:
    - 1.14.x
    - master


# only clone the latest commit
git:
    depth: 1

# to prevent sudo using the secure_path we using -E option
# and letting it use the users env variables, not doing this results in
# a PATH bug and go command not found
script:
    - sudo -E env "PATH=$PATH" go test -v ./...


